apiVersion: v1
kind: Service
metadata:
  name: dolt-primary-remotesapi
  namespace: dolt-cluster-example
spec:
  selector:
    app: dolt
    dolthub.com/cluster_role: primary
  ports:
    - name: tcp
      port: 8090          # External port
      targetPort: 8090    # Container port (RemotesAPI used gRPC over tcp port 8090)
      protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: dolt-primary-remotesapi-tcp
  namespace: dolt-cluster-example
spec:
  entryPoints:
    - dolt
  routes:
    # later, we'll use TLS w/ SNI Routing on port 80, e.g: HostSNI(`primary.dolt.test`)
    # For plain TCP routers, the HostSNI rule must be set to * per Traefik docs.
    - match: HostSNI(`*`) 
      services:
        - name: dolt-primary-remotesapi
          port: tcp