apiVersion: apps/v1
kind: Deployment
metadata:
  name: dolt-workbench
  namespace: dolt-cluster-example
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dolt-workbench
  template:
    metadata:
      labels:
        app: dolt-workbench
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64    
      containers:
      - name: dolt-workbench
        image: priley86/dolt-workbench:arm64
        env:
        - name: GRAPHQLAPI_URL
          value: "http://api.dolt.test/graphql"
        ports:
        - containerPort: 9002
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: dolt-workbench
  namespace: dolt-cluster-example
spec:
  selector:
    app: dolt-workbench
  ports:
    - name: graphql
      port: 9002
      targetPort: 9002
    - name: web
      port: 3000
      targetPort: 3000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dolt-workbench-app-ingress
  namespace: dolt-cluster-example
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: app.dolt.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dolt-workbench
            port:
              name: web

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dolt-workbench-api-ingress
  namespace: dolt-cluster-example
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
  - host: api.dolt.test
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dolt-workbench
            port:
              name: graphql
