apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - name: 3306-3306
    # Optional field
    # By default and for convenience, the Kubernetes control plane
    # will allocate a port from a range (default: 30000-32767)  
    nodePort: 30080
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: nginx
  type: NodePort